# Generated by Django 4.2 on 2025-07-31 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_id', models.CharField(max_length=36, unique=True)),
                ('marital_status', models.CharField(max_length=20)),
                ('house_ownership', models.CharField(max_length=20)),
                ('car_ownership', models.CharField(max_length=10)),
                ('profession', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('current_job_years', models.IntegerField()),
                ('current_house_years', models.IntegerField()),
                ('income', models.IntegerField()),
                ('age', models.IntegerField()),
                ('result', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Prediction Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
